version: "3"
services:
    node-red:
        container_name: node-red
        restart: always
        image: nodered/node-red:3.0.2-18-minimal
        environment:
            - NODE_RED_ENABLE_PROJECTS=true
        volumes:
            - ./node-red/etc:/data
        ports:
            - 1880:1880
        networks:
            - node-red-network


networks:
    node-red-network:
        driver: bridge
